name = "cloudfl"

main = "./server.ts"
assets = "./public/build"
workers_dev = true
compatibility_date = "2023-04-20"
# might be easier to debug without minify
minify = true


[vars]
USER_SESSION_SECRET="testing123"
USER_COOKIE_SECRET="testing123"

[env.development]

[env.production]

[[kv_namespaces]]
binding = "theform"
id = "7e6ae0281b6343f0859b258fecdd9adf"
preview_id = "042ecf04833d49f7be136850c4758d39"

